using System;
using System.Collections.Generic;
using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.Forms.UI;

[GenerateTypedNameReferences]
public sealed partial class FormFieldPickerWindow : DefaultWindow
{
    public event Action<string>? OnConfirmed;
    private List<string> _options = new();

    public FormFieldPickerWindow()
    {
        RobustXamlLoader.Load(this);
        Confirm.OnPressed += _ =>
        {
            var selected = Options.GetSelected().FirstOrDefault();
            var choice = selected?.Text ?? string.Empty;
            var text = string.IsNullOrWhiteSpace(Custom.Text) ? choice : Custom.Text;
            OnConfirmed?.Invoke(text);
        };
        Search.OnTextChanged += _ => Refresh();
    }

    public void Populate(List<string> options)
    {
        _options = options;
        Refresh();
        Confirm.Text = Loc.GetString("paper-field-picker-confirm");
    }

    private void Refresh()
    {
        Options.Clear();
        IEnumerable<string> filtered;
        if (string.IsNullOrWhiteSpace(Search.Text))
            filtered = _options;
        else
            filtered = _options.Where(o => o.Contains(Search.Text, StringComparison.CurrentCultureIgnoreCase));
        foreach (var option in filtered)
            Options.AddItem(option);
        if (Options.Count > 0)
            Options[0].Selected = true;
    }
}
