using System;
using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.Input;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Utility;
using Content.Shared.Forms;
using Robust.Shared.Localization;

namespace Content.Client.Forms.UI;

[GenerateTypedNameReferences]
public sealed partial class FormWindow : BaseWindow
{
    [Dependency] private readonly IInputManager _inputManager = default!;

    public event Action<string>? OnSaved;
    public event Action<string>? OnPlaceholderClicked;

    private Dictionary<string, List<string>> _dropdown = new();
    private Dictionary<string, string> _selection = new();

    public FormWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += _ => Close();

        InputField.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.MultilineTextSubmit)
            {
                RunOnSaved();
                args.Handle();
            }
            else if (args.Function == EngineKeyFunctions.UIClick)
            {
                var word = GetWordAtCursor();
                if (word != null)
                {
                    OnPlaceholderClicked?.Invoke(word);
                    args.Handle();
                }
            }
        };

        SaveButton.OnPressed += _ => RunOnSaved();
        SaveButton.Text = Loc.GetString("paper-ui-save-button",
            ("keybind", _inputManager.GetKeyFunctionButtonString(EngineKeyFunctions.MultilineTextSubmit)));
    }

    public TextEdit Input => InputField;

    private int _maxInputLength = -1;
    public int MaxInputLength
    {
        get => _maxInputLength;
        set
        {
            _maxInputLength = value;
            UpdateFillState();
        }
    }

    private void RunOnSaved()
    {
        OnSaved?.Invoke(Rope.Collapse(Input.TextRope));
    }

    public void Populate(FormDocumentComponent.FormBoundUserInterfaceState state)
    {
        Input.TextRope = Rope.Leaf.Empty;
        Input.CursorPosition = new TextEdit.CursorPos();
        Input.InsertAtCursor(state.Text);
        _dropdown = state.Dropdown;
        _selection = state.Selection;
    }

    private string? GetWordAtCursor()
    {
        var text = Rope.Collapse(Input.TextRope);
        if (text.Length == 0)
            return null;

        var index = Math.Clamp(Input.CursorPosition.Index, 0, text.Length);

        foreach (var (placeholder, value) in _selection)
        {
            var search = 0;
            while ((search = text.IndexOf(value, search, StringComparison.Ordinal)) != -1)
            {
                var end = search + value.Length;
                if (index >= search && index <= end)
                    return placeholder;
                search = end;
            }
        }

        foreach (var placeholder in _dropdown.Keys)
        {
            var search = 0;
            while ((search = text.IndexOf(placeholder, search, StringComparison.Ordinal)) != -1)
            {
                var end = search + placeholder.Length;
                if (index >= search && index <= end)
                    return placeholder;
                search = end;
            }
        }

        return null;
    }

    private void UpdateFillState()
    {
        if (_maxInputLength != -1)
        {
            SaveButton.Disabled = Input.TextLength > _maxInputLength;
        }
        else
        {
            SaveButton.Disabled = false;
        }
    }
}
