using System;
using System.Collections.Generic;
using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.Forms.UI;

[GenerateTypedNameReferences]
public sealed partial class FormPickerWindow : DefaultWindow
{
    public event Action<int>? OnFormSelected;

    private List<string> _options = new();

    public FormPickerWindow()
    {
        RobustXamlLoader.Load(this);
        Confirm.OnPressed += _ =>
        {
            var selected = Options.GetSelected().FirstOrDefault();
            if (selected != null && selected.Metadata is int id)
                OnFormSelected?.Invoke(id);
        };
        Search.OnTextChanged += _ => Refresh();
        Confirm.Text = Loc.GetString("paper-field-picker-confirm");
    }

    public void Update(IReadOnlyList<string> options)
    {
        _options = options.ToList();
        Refresh();
    }

    private void Refresh()
    {
        Options.Clear();
        for (var i = 0; i < _options.Count; i++)
        {
            var option = _options[i];
            if (!string.IsNullOrWhiteSpace(Search.Text) &&
                !option.Contains(Search.Text, StringComparison.CurrentCultureIgnoreCase))
                continue;
            Options.AddItem(option, metadata: i);
        }

        if (Options.Count > 0)
            Options[0].Selected = true;
    }
}
