using System;
using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class PaperFieldPickerWindow : DefaultWindow
{
    public event Action<string>? OnConfirmed;
    private List<string> _options = new();

    public PaperFieldPickerWindow()
    {
        RobustXamlLoader.Load(this);
        Confirm.OnPressed += _ =>
        {
            var text = string.IsNullOrWhiteSpace(Custom.Text)
                ? (_options.Count > 0 ? _options[Options.GetIdx(Options.SelectedId)] : string.Empty)
                : Custom.Text;
            OnConfirmed?.Invoke(text);
        };
    }

    public void Populate(List<string> options)
    {
        _options = options;
        Options.Clear();
        foreach (var option in options)
            Options.AddItem(option);
        if (options.Count > 0)
            Options.Select(0);
        Confirm.Text = Loc.GetString("paper-field-picker-confirm");
    }
}
