using System;
using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class PaperFormPickerWindow : DefaultWindow
{
    public event Action<int>? OnFormSelected;

    public PaperFormPickerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(IReadOnlyList<string> options)
    {
        ButtonContainer.DisposeAllChildren();
        for (var i = 0; i < options.Count; i++)
        {
            var index = i;
            var button = new Button { Text = options[i] };
            button.OnPressed += _ => OnFormSelected?.Invoke(index);
            ButtonContainer.AddChild(button);
        }
    }
}
